// Geometrical parameters
Nr = 2;
Nz = 2;
lr = 0.003;
lz = 0.012;
ei = 0.5*0.001; // en gui "ei" es "Aum_ent". Aum_ent = 2*ei
es = 0.001;
Rw = 0.3;
es_extra = {0.0, 0.0};

//Nucleo
Core_R_int = 0.29;
Core_R_out = 0.33999999999999997;
Core_Z     = 0.05;


// Geometrical & physical entities numbering
p0 = 100000000;
l0 = 100000000;
ll0 = 100000000;
phys0 = 100000000;
phyl0 = 150000000;
ioffset  = 100000000;
bboffset = 200000000;
coffset  = 1000000000;

ppoffset = 10000000;
wboffset = 20000000;

// Physical parameters
EPS_TURNS = 3.0; // epsr_AIR / OIL
EPS_DISK = 2.6; // epsr_INSUL
eps_ppan = 4.7; // epsr_INSUL

Nwb  = 0;
Npp  = 0;

ppdoffset	    = 30000000;
esroffset	    = 30000000;
esr_ins_offset	= 300;
end_ring_offset = 40000000;

Nesr    = 0;
N_end_ring    = 0;

LIC_FLAG  	= 0;
